version: '3.7'
services:
  slave_player_service:
    build:
      context: .
    restart: 'no'
    volumes:
      - './:/app'
    ports:
      - '4001:4001'
    networks:
      - proradio

networks:
  proradio:
    name: proradio
